---
# file: roles/veracrypt/tasks/get_version.yml

- name: Check GitHub API for latest VeraCrypt release
  ansible.builtin.uri:
    url: https://api.github.com/repos/veracrypt/VeraCrypt/releases/latest
    return_content: true
  register: veracrypt_version
  failed_when: veracrypt_version is failed or veracrypt_version.json.tag_name is not defined

- name: Set VeraCrypt version
  ansible.builtin.set_fact:
    veracrypt_package_version: "{{ veracrypt_version.json.tag_name.split('_')[1] }}"

- name: Show VeraCrypt version
  ansible.builtin.debug:
    var: veracrypt_package_version
