---
# file: roles/veracrypt/tasks/main.yml

- name: Gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
      skip: true
  tags: vars

- name: Install dependencies
  ansible.builtin.include_tasks: dependencies.yml
  when: veracrypt_package_state != "absent"

- name: Detect latest VeraCrypt version
  ansible.builtin.include_tasks: get-version.yml
  when:
    - veracrypt_package_version == "latest"
    - veracrypt_package_state != "absent"

- name: "Set package name"
  ansible.builtin.set_fact:
    veracrypt_package_name: "{{ 'veracrypt-console' if veracrypt_package_console_only == true else 'veracrypt' }}"

- name: OS specific setup.
  ansible.builtin.include_tasks: "setup-{{ ansible_facts.os_family }}.yml"
  when: veracrypt_package_state != "absent"

- name: OS specific uninstall.
  ansible.builtin.include_tasks: "uninstall.yml"
  when: veracrypt_package_state == "absent"
