---
# file: roles/veracrypt/tasks/repo-Debian.yml

- name: "Debian: Add an Apt signing key for Alexander Pozdnyakov"
  become: true
  ansible.builtin.apt_key:
    url: https://notesalexp.org/debian/alexp_key.asc
    state: present

- name: "Debian: Add VeraCrypt repository"
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://notesalexp.org/debian/{{ ansible_distribution_release }}/ {{ ansible_distribution_release }} main"
    update_cache: true
    state: present
    mode: "0644"
  register: veracrypt_repo
