---
# file: roles/veracrypt/tasks/repo-Fedora.yml

- name: "Fedora: Add RPM Sphere repository"
  become: true
  ansible.builtin.yum_repository:
    name: rpmsphere
    description: RPM Sphere - Basearch
    baseurl: https://github.com/rpmsphere/$basearch/raw/master/
    repo_gpgcheck: "no"
    gpgcheck: "no"
    enabled: "yes"
  register: veracrypt_repo
