---
# file: roles/veracrypt/tasks/setup-RedHat.yml

- name: Set RedHat architecture
  ansible.builtin.set_fact:
    veracrypt_architecture: "{{ ansible_architecture }}"
  when: veracrypt_architecture is not defined
    
- name: "CentOS 7: Define package URL"
  ansible.builtin.set_fact:
    veracrypt_package: "https://launchpad.net/veracrypt/trunk/\
      {{ veracrypt_package_version }}\
      /+download/\
      {{ veracrypt_package_name }}\
      -{{ veracrypt_package_version }}\
      -CentOS-7\
      -{{ veracrypt_architecture }}.rpm"
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version | int == 7

- name: "RedHat: Define package URL"
  ansible.builtin.set_fact:
    veracrypt_package: "https://launchpad.net/veracrypt/trunk/\
      {{ veracrypt_package_version }}\
      /+download/\
      {{ veracrypt_package_name }}\
      -{{ veracrypt_package_version }}\
      -CentOS-8\
      -{{ veracrypt_architecture }}.rpm"
  when: (ansible_distribution != "CentOS") or
    ((ansible_distribution == "CentOS") and (ansible_distribution_major_version | int > 7))

- name: Show package URL
  ansible.builtin.debug:
    var: veracrypt_package

- name: "RedHat: Install RPM GPG Key"
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://www.idrix.fr/VeraCrypt/VeraCrypt_PGP_public_key.asc

- name: "RedHat: Install veracrypt"
  become: true
  ansible.builtin.yum:
    name: "{{ veracrypt_package }}"
    state: "{{ veracrypt_package_state }}"
