---
# file: roles/veracrypt/tasks/setup-Debian.yml

- name: "Debian: Install dependencies"
  become: true
  ansible.builtin.apt:
    name: "{{ veracrypt_dependencies }}"
    state: present
    update_cache: true

- name: "Debian: Define package URL"
  ansible.builtin.set_fact:
    veracrypt_package: "https://launchpad.net/veracrypt/trunk/{{ veracrypt_package_version }}/+download/veracrypt-{{ veracrypt_package_version }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-amd64.deb"
  when:
    - ansible_distribution == "Debian"

- name: "Ubuntu: Define package URL"
  ansible.builtin.set_fact:
    veracrypt_package: "https://launchpad.net/veracrypt/trunk/{{ veracrypt_package_version }}/+download/veracrypt-{{ veracrypt_package_version }}-{{ ansible_distribution }}-{{ ansible_distribution_version }}-amd64.deb"
  when:
    - ansible_distribution == "Ubuntu"

- name: Show package URL
  ansible.builtin.debug:
    var: veracrypt_package

- name: "Debian: Install veracrypt"
  become: true
  ansible.builtin.apt:
    deb: "{{ veracrypt_package }}"
    state: "{{ veracrypt_package_state }}"
    install_recommends: false
