---
# file: roles/veracrypt/molecule/default/verify.yml

- name: Verify
  hosts: all
  tasks:
    - name: Show OS
      ansible.builtin.debug:
        msg: "{{ ansible_facts.distribution }} - {{ ansible_facts.distribution_version }}"

    - name: Gather installed package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Assert veracrypt-console is installed
      ansible.builtin.assert:
        that:
          - "'veracrypt-console' in ansible_facts.packages"
        fail_msg: "veracrypt is not installed"
        success_msg: "veracrypt {{ ansible_facts.packages['veracrypt-console'][0].version }} is installed"
